document.writeln("hai")
document.writeln("helloworld")
document.writeln("bye")
document.write('<br>')
document.writeln("<h1>welcome</h1>")
document.writeln("<h2>goodboy</h2>")
document.write(`<h1 style=color:red>hello</h1>`)
console.log('hai')
console.error("its is a worng")
console.warn('be carefull')